using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Defando.Models;

/// <summary>
/// Represents an application user with role-based permissions.
/// </summary>
[Table("users")]
public class User
{
    /// <summary>
    /// Unique identifier generated by the database.
    /// </summary>
    [Key]
    [Column("user_id")]
    public int UserId { get; set; }

    /// <summary>
    /// Unique username used for authentication.
    /// </summary>
    [Required]
    [MaxLength(50)]
    [Column("username")]
    public string Username { get; set; } = string.Empty;

    /// <summary>
    /// BCrypt hashed password.
    /// </summary>
    [Required]
    [MaxLength(255)]
    [Column("password_hash")]
    public string PasswordHash { get; set; } = string.Empty;

    /// <summary>
    /// Full name shown across the system.
    /// </summary>
    [Required]
    [MaxLength(150)]
    [Column("full_name")]
    public string FullName { get; set; } = string.Empty;

    /// <summary>
    /// Optional email address used for notifications.
    /// </summary>
    [MaxLength(150)]
    [Column("email")]
    public string? Email { get; set; }

    /// <summary>
    /// Role describing the user responsibilities.
    /// </summary>
    [Required]
    [MaxLength(30)]
    [Column("role")]
    public string Role { get; set; } = "read_only";

    /// <summary>
    /// Indicates whether the user can sign in.
    /// </summary>
    [Column("is_active")]
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// Timestamp when the user was created.
    /// </summary>
    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Timestamp of the last successful login.
    /// </summary>
    [Column("last_login")]
    public DateTime? LastLogin { get; set; }

    /// <summary>
    /// Number of consecutive failed login attempts.
    /// </summary>
    [Column("failed_login_attempts")]
    public int FailedLoginAttempts { get; set; } = 0;

    /// <summary>
    /// Timestamp when the account was locked due to failed login attempts.
    /// </summary>
    [Column("locked_until")]
    public DateTime? LockedUntil { get; set; }

    /// <summary>
    /// Folders created by the user.
    /// </summary>
    public virtual ICollection<Folder> CreatedFolders { get; set; } = new List<Folder>();

    /// <summary>
    /// Documents currently locked by the user.
    /// </summary>
    public virtual ICollection<Document> LockedDocuments { get; set; } = new List<Document>();

    /// <summary>
    /// Documents uploaded by the user.
    /// </summary>
    public virtual ICollection<Document> UploadedDocuments { get; set; } = new List<Document>();

    /// <summary>
    /// Document versions created by the user.
    /// </summary>
    public virtual ICollection<DocumentVersion> DocumentVersions { get; set; } = new List<DocumentVersion>();

    /// <summary>
    /// Audit events recorded for this user actions.
    /// </summary>
    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    /// <summary>
    /// Outgoing correspondences created by the user.
    /// </summary>
    public virtual ICollection<Outgoing> OutgoingRecords { get; set; } = new List<Outgoing>();

    /// <summary>
    /// Incoming correspondences created by the user.
    /// </summary>
    public virtual ICollection<Incoming> IncomingRecords { get; set; } = new List<Incoming>();

    /// <summary>
    /// Tasks assigned to the user.
    /// </summary>
    public virtual ICollection<TaskItem> AssignedTasks { get; set; } = new List<TaskItem>();

    /// <summary>
    /// Tasks created by the user.
    /// </summary>
    public virtual ICollection<TaskItem> DelegatedTasks { get; set; } = new List<TaskItem>();

    /// <summary>
    /// Comments authored by the user.
    /// </summary>
    public virtual ICollection<TaskComment> TaskComments { get; set; } = new List<TaskComment>();

    /// <summary>
    /// Shared links created by the user.
    /// </summary>
    public virtual ICollection<SharedLink> SharedLinks { get; set; } = new List<SharedLink>();

    /// <summary>
    /// Emails sent by the user.
    /// </summary>
    public virtual ICollection<EmailLog> EmailLogs { get; set; } = new List<EmailLog>();
}

